

### sign up

POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "xxx3@gmail.com",
    "password": "111"
}
### sign in

POST http://localhost:3000/auth/signin
content-type: application/json

{
    "email": "xxx3@gmail.com",
    "password": "111111"
}


### Find id

get http://localhost:3000/auth/5



### find all user

get http://localhost:3000/auth?email=123@gmail.com


### find all user

get http://localhost:3000/auth/alluser

### Delete

Delete http://localhost:3000/auth/1


### Update

PATCH http://localhost:3000/auth/2
Content-Type: application/json

{
    "email" : "bbbb@gmail.com",
    "password" : "yeeha"
}


